at.noise_removal(image)
at.mean_filter(kernal_size, img)
at.gaussian_filter(kernal_size, img, sigma_x, sigma_y)
at.median_filter(kernal_size, img)
at.conservative_filter(img, filter_size)
at.laplacian_filter(img)
at.laplacian_of_gaussian_filtering(kernal_size, img, sigma_x, sigma_y)
at.low_pass_dft(img)
at.crimmins_speckle_removal(data)
at.unsharp_filter(img, radius=2, percent=150)
